addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  global:
    - PROJECT="{{ Project Name }}"
    - VERSION="{{ Version }}"
    - RELEASE="{{ Release }}"
    - BRANCH_PROD="master"
    - BRANCH_DOC="gh-pages"
    - TESTS="0"
    - LINT_CHECK="0"
    - DOCS="0"
    - PYPI="0"
    # Generate this per repo with the following:
    #   travis encrypt 'PYPI_PASSWORD="$PYPI_PASSWORD"'-r LasLabs/repo-name
    - secure: "$PYPI_TOKEN"
  matrix:
    - TESTS="1"
    - PYPI="1"
    - DOCS="1"

install:
  - git clone --depth=1 https://github.com/LasLabs/python-quality-tools.git ${HOME}/python-quality-tools
  - export PATH=${HOME}/python-quality-tools/travis:${PATH}
  - travis_install

script:
  - travis_run

after_success:
  - travis_after_success
